#!/bin/bash
export NUMBA_THREADING_LAYER=workqueue
export UMAP_CDW_DATA=../data
export NUMBA_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
../venv/bin/python -m pdb analyze_similar_features.py --quick-test --min_half_window_length=12 --max_half_window_length=12 --window_length_steps=1
