#!/bin/bash

#PBS -l nodes=1:ppn=1:gpus=1
#PBS -A cnm83860

#PBS -m ea

# change into the directory where qsub will be executed
cd $PBS_O_WORKDIR

module load cuda
module load gcc

export NUMBA_THREADING_LAYER=workqueue
export UMAP_CDW_DATA=data
venv/bin/python test.py
