#!/bin/bash

#PBS -l nodes=1:ppn=32:gen8
#PBS -A cnm83860

#PBS -m ea

# change into the directory where qsub will be executed
cd $PBS_O_WORKDIR

module load cuda
module load gcc

export NUMBA_NUM_THREADS=$PBS_NP
export MKL_NUM_THREADS=$PBS_NP
export OMP_NUM_THREADS=$PBS_NP

export NUMBA_THREADING_LAYER=workqueue
export UMAP_CDW_DATA=data
venv/bin/python test.py --min_half_window_length=6 --max_half_window_length=84 --window_length_steps=15
