#!/bin/bash
export NUMBA_THREADING_LAYER=workqueue
export UMAP_CDW_DATA=../data
../venv/bin/python test.py --min_half_window_length=12 --max_half_window_length=12 --window_length_steps=1 --quick-test --no-save
