#!/bin/bash
export NUMBA_THREADING_LAYER=workqueue
export UMAP_CDW_DATA=../data
export NUMBA_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
../venv/bin/python no_diagonal.py --half-window-lengths 6 --window-stepsize-ratios 2
